[build]
  command   = "npm run build"
  publish   = ".next"

[[redirects]]
  from = "/certified"
  to = "/certified"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/dashboard"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"
